global_settings = {
    'theme': 'dark',
    'language': 'en-US',
    'timezone': 'UTC',
    'date_format': 'MM/DD/YYYY',
    'time_format': '24h',
    'currency': 'USD',
    'measurement': 'imperial',
    'notifications': True,
    'sound_enabled': True,
    'haptic_feedback': False,
    'auto_save': True,
    'save_interval': 300,
    'backup_enabled': False,
    'max_file_size': 10485760,
    'compression': True,
    'encryption': False,
    'debug_mode': False,
    'analytics': True,
    'crash_reports': True,
    'beta_features': False,
    'api_timeout': 30,
    'retry_attempts': 3,
    'cache_size': 52428800,
    'history_limit': 100,
    'undo_levels': 50,
    'font_size': 14,
    'font_family': 'Roboto',
    'line_height': 1.5,
    'tab_size': 4,
    'word_wrap': True,
    'show_whitespace': False,
    'show_line_numbers': True,
    'highlight_current_line': True,
    'bracket_matching': True,
    'auto_indent': True,
    'trim_trailing_whitespace': True,
    'insert_final_newline': True,
    'detect_indentation': True,
    'spell_check': False,
    'minimap_enabled': True,
    'breadcrumbs': True,
    'sticky_scroll': False,
    'smooth_scrolling': True,
    'mouse_wheel_zoom': False,
    'cursor_style': 'line',
    'cursor_blink': 'blink',
    'selection_highlight': True,
    'find_in_selection': False,
    'search_case_sensitive': False,
    'search_whole_word': False,
    'search_regex': False
}

user_preferences = {
    'theme': 'light',
    'language': 'es-MX',
    'notifications': False,
    'font_size': 16,
    'tab_size': 2,
    'show_line_numbers': False,
    'auto_indent': False,
    'username': 'jdoe',
    'email': 'jdoe@example.com',
    'avatar': 'https://avatar.url/jdoe',
    'bio': 'Software developer',
    'location': 'Austin, TX',
    'website': 'https://jdoe.dev',
    'twitter': '@jdoe',
    'github': 'jdoe',
    'linkedin': 'jdoe',
    'display_name': 'John Doe',
    'profile_visibility': 'public',
    'show_email': False,
    'show_location': True,
    'allow_messages': True,
    'allow_friend_requests': True,
    'show_online_status': False,
    'two_factor_enabled': True,
    'login_alerts': True,
    'password_last_changed': '2024-11-15',
    'account_created': '2020-03-22',
    'last_login': '2025-12-03',
    'login_count': 1247,
    'preferred_contact': 'email',
    'newsletter_subscribed': False,
    'marketing_emails': False,
    'product_updates': True,
    'weekly_digest': True
}

project_config = {
    'project_name': 'Awesome App',
    'version': '2.3.1',
    'build': 847,
    'environment': 'development',
    'debug_mode': True,
    'verbose_logging': True,
    'log_level': 'DEBUG',
    'api_timeout': 60,
    'retry_attempts': 5,
    'database_host': 'localhost',
    'database_port': 5432,
    'database_name': 'awesome_dev',
    'database_user': 'dev_user',
    'database_pool_size': 20,
    'cache_enabled': True,
    'cache_ttl': 3600,
    'session_timeout': 7200,
    'max_upload_size': 52428800,
    'allowed_file_types': ['.jpg', '.png', '.pdf', '.docx'],
    'rate_limit': 1000,
    'rate_window': 3600,
    'cors_enabled': True,
    'cors_origins': ['http://localhost:3000', 'http://localhost:8080'],
    'jwt_expiry': 86400,
    'refresh_token_expiry': 604800,
    'password_min_length': 8,
    'password_require_uppercase': True,
    'password_require_lowercase': True,
    'password_require_numbers': True,
    'password_require_special': True,
    'max_login_attempts': 5,
    'lockout_duration': 1800,
    'email_verification_required': True,
    'admin_email': 'admin@awesome.app',
    'support_email': 'support@awesome.app',
    'smtp_host': 'smtp.gmail.com',
    'smtp_port': 587,
    'smtp_use_tls': True,
    'default_from_email': 'noreply@awesome.app',
    'pagination_page_size': 25,
    'search_results_limit': 100,
    'thumbnail_size': [150, 150],
    'image_quality': 85,
    'video_max_duration': 600,
    'audio_max_duration': 1800
}

workspace_settings = {
    'workspace_name': 'Frontend Team',
    'workspace_id': 'ws_87df23kj',
    'created_by': 'jdoe',
    'created_at': '2024-01-10',
    'member_count': 12,
    'project_count': 8,
    'storage_used': 8589934592,
    'storage_limit': 107374182400,
    'theme': 'ocean',
    'sidebar_position': 'left',
    'sidebar_collapsed': False,
    'panel_position': 'bottom',
    'panel_height': 300,
    'terminal_shell': 'bash',
    'git_enabled': True,
    'git_auto_fetch': True,
    'git_auto_fetch_interval': 180,
    'extensions_enabled': True,
    'extension_auto_update': True,
    'telemetry_enabled': False,
    'update_channel': 'stable',
    'proxy_enabled': False,
    'http_proxy': '',
    'https_proxy': '',
    'no_proxy': '',
    'certificate_verification': True,
    'default_branch': 'main',
    'merge_strategy': 'merge',
    'commit_signing': True,
    'gpg_key': 'ABC123DEF456',
    'ssh_key': '~/.ssh/id_rsa',
    'code_review_required': True,
    'min_reviewers': 2,
    'auto_merge_enabled': False,
    'branch_protection': True,
    'protected_branches': ['main', 'develop', 'staging'],
    'ci_enabled': True,
    'ci_provider': 'github-actions',
    'deployment_auto': False,
    'deployment_environments': ['dev', 'staging', 'production'],
    'monitoring_enabled': True,
    'error_tracking': 'sentry',
    'analytics_provider': 'mixpanel',
    'feature_flags_enabled': True,
    'ab_testing_enabled': False
}

session_data = {
    'session_id': 'sess_9k2j3h4g5f6d7s8a',
    'user_id': 'usr_jdoe_123',
    'ip_address': '192.168.1.105',
    'user_agent': 'Mozilla/5.0 Chrome/120.0',
    'started_at': '2025-12-04T14:23:17Z',
    'last_activity': '2025-12-04T16:45:32Z',
    'expires_at': '2025-12-04T18:23:17Z',
    'is_authenticated': True,
    'is_admin': False,
    'permissions': ['read', 'write', 'comment', 'share'],
    'active_project': 'proj_awesome_847',
    'open_files': ['src/index.js', 'src/App.jsx', 'styles/main.css'],
    'current_file': 'src/App.jsx',
    'cursor_position': [142, 28],
    'scroll_position': 1840,
    'unsaved_changes': True,
    'clipboard': 'const handleClick = () => {}',
    'search_history': ['useState', 'useEffect', 'props.children'],
    'recent_commands': ['npm install', 'git commit', 'npm run dev'],
    'breakpoints': [23, 45, 67, 89],
    'watches': ['userData', 'isLoading', 'error'],
    'terminal_count': 2,
    'split_editor': True,
    'layout': 'horizontal',
    'zoom_level': 1.1,
    'sidebar_width': 280,
    'activity_bar_visible': True,
    'status_bar_visible': True,
    'menu_bar_visible': True,
    'tabs_visible': True,
    'breadcrumbs_visible': True,
    'minimap_visible': False
}

temporary_overrides = {
    'debug_mode': False,
    'verbose_logging': False,
    'cache_enabled': False,
    'auto_save': False,
    'notifications': True,
    'sound_enabled': False,
    'performance_mode': True,
    'reduced_motion': True,
    'high_contrast': False,
    'screen_reader': False,
    'keyboard_only': False,
    'focus_mode': True,
    'zen_mode': False,
    'presentation_mode': False
}

feature_flags = {
    'new_editor': False,
    'collaborative_editing': True,
    'ai_autocomplete': True,
    'voice_commands': False,
    'gesture_controls': False,
    'vr_mode': False,
    'dark_theme_v2': True,
    'new_file_explorer': True,
    'improved_search': True,
    'better_git_integration': True,
    'plugin_marketplace_v2': False,
    'native_mobile_app': False,
    'web_assembly_support': True,
    'gpu_acceleration': False,
    'multi_cursor_v2': True,
    'inline_debugging': True,
    'live_preview': True,
    'code_lens': True,
    'bracket_colorization': True,
    'sticky_headers': True,
    'type_checking': True,
    'auto_imports': True,
    'smart_rename': True,
    'extract_refactoring': True,
    'test_generation': False,
    'documentation_generation': True,
    'accessibility_checker': False,
    'performance_profiler': True,
    'security_scanner': False,
    'dependency_analyzer': True
}

api_config = {
    'api_version': 'v3',
    'base_url': 'https://api.awesome.app',
    'auth_endpoint': '/auth/login',
    'refresh_endpoint': '/auth/refresh',
    'user_endpoint': '/users',
    'project_endpoint': '/projects',
    'files_endpoint': '/files',
    'search_endpoint': '/search',
    'api_key': 'ak_live_2h3k4j5h6g7f8d9s0a',
    'api_secret': 'secret_87df23kj92jf83kd',
    'webhook_url': 'https://hooks.awesome.app/events',
    'webhook_secret': 'whsec_92jd83kf74js93kd',
    'rate_limit': 5000,
    'rate_window': 3600,
    'burst_limit': 100,
    'concurrent_requests': 10,
    'timeout': 30,
    'connect_timeout': 10,
    'read_timeout': 30,
    'write_timeout': 30,
    'keep_alive': True,
    'compression': True,
    'follow_redirects': True,
    'max_redirects': 3,
    'verify_ssl': True,
    'client_cert': None,
    'user_agent': 'AwesomeApp/2.3.1',
    'accept': 'application/json',
    'content_type': 'application/json',
    'charset': 'utf-8'
}

database_settings = {
    'driver': 'postgresql',
    'host': 'db.awesome.app',
    'port': 5432,
    'database': 'awesome_prod',
    'username': 'prod_user',
    'password': 'secure_password_here',
    'ssl_mode': 'require',
    'ssl_cert': '/path/to/cert.pem',
    'connection_pool_min': 5,
    'connection_pool_max': 50,
    'connection_timeout': 30,
    'idle_timeout': 600,
    'max_lifetime': 3600,
    'query_timeout': 60,
    'statement_timeout': 30000,
    'lock_timeout': 10000,
    'application_name': 'awesome_app',
    'search_path': 'public',
    'timezone': 'UTC',
    'encoding': 'UTF8',
    'log_queries': True,
    'log_slow_queries': True,
    'slow_query_threshold': 1000,
    'explain_queries': False,
    'auto_vacuum': True,
    'max_connections': 200,
    'shared_buffers': '256MB',
    'effective_cache_size': '1GB',
    'work_mem': '4MB',
    'maintenance_work_mem': '64MB',
    'checkpoint_completion_target': 0.9,
    'wal_buffers': '16MB',
    'default_statistics_target': 100,
    'random_page_cost': 1.1,
    'effective_io_concurrency': 200,
    'min_wal_size': '1GB',
    'max_wal_size': '4GB'
}

cache_config = {
    'provider': 'redis',
    'host': 'cache.awesome.app',
    'port': 6379,
    'password': 'cache_password',
    'database': 0,
    'key_prefix': 'awesome:',
    'ttl': 3600,
    'max_memory': '512mb',
    'eviction_policy': 'allkeys-lru',
    'max_connections': 50,
    'socket_timeout': 5,
    'socket_connect_timeout': 5,
    'socket_keepalive': True,
    'health_check_interval': 30,
    'retry_on_timeout': True,
    'max_retry_attempts': 3,
    'cluster_mode': False,
    'sentinel_mode': False,
    'persistence': True,
    'save_frequency': [900, 1, 300, 10, 60, 10000],
    'compression_enabled': True,
    'compression_threshold': 1024,
    'serializer': 'json',
    'deserializer': 'json'
}

monitoring_config = {
    'provider': 'datadog',
    'api_key': 'dd_api_key_92jd83kf74js93kd',
    'app_key': 'dd_app_key_47ks93jd82kf74js',
    'environment': 'production',
    'service_name': 'awesome-app',
    'version': '2.3.1',
    'metrics_enabled': True,
    'traces_enabled': True,
    'logs_enabled': True,
    'profiling_enabled': True,
    'sampling_rate': 0.1,
    'trace_sample_rate': 1.0,
    'log_level': 'INFO',
    'log_format': 'json',
    'custom_tags': {'team': 'frontend', 'region': 'us-east-1'},
    'alert_email': 'alerts@awesome.app',
    'alert_slack': '#alerts-prod',
    'alert_pagerduty': 'pd_key_83jd92kf74js93kd',
    'uptime_monitoring': True,
    'synthetic_tests': True,
    'rum_enabled': True,
    'error_tracking': True,
    'performance_monitoring': True,
    'infrastructure_monitoring': True,
    'network_monitoring': False,
    'security_monitoring': True,
    'apm_enabled': True,
    'cost_tracking': False
}

security_config = {
    'encryption_algorithm': 'AES-256-GCM',
    'encryption_key': 'enc_key_92jd83kf74js93kd47ks93jd82kf74js',
    'hashing_algorithm': 'bcrypt',
    'hashing_rounds': 12,
    'salt_rounds': 10,
    'jwt_algorithm': 'RS256',
    'jwt_public_key': '-----BEGIN PUBLIC KEY-----',
    'jwt_private_key': '-----BEGIN PRIVATE KEY-----',
    'csrf_protection': True,
    'csrf_token_length': 32,
    'xss_protection': True,
    'content_security_policy': "default-src 'self'",
    'x_frame_options': 'DENY',
    'x_content_type_options': 'nosniff',
    'strict_transport_security': 'max-age=31536000',
    'referrer_policy': 'strict-origin-when-cross-origin',
    'permissions_policy': "geolocation=(), microphone=()",
    'cookie_secure': True,
    'cookie_httponly': True,
    'cookie_samesite': 'Strict',
    'session_fixation_protection': True,
    'sql_injection_protection': True,
    'command_injection_protection': True,
    'path_traversal_protection': True,
    'file_upload_validation': True,
    'max_file_uploads': 10,
    'allowed_hosts': ['awesome.app', 'www.awesome.app'],
    'blocked_ips': [],
    'allowed_ips': [],
    'geo_blocking': False,
    'rate_limiting': True,
    'brute_force_protection': True,
    'ddos_protection': False,
    'waf_enabled': True
}

notification_settings = {
    'email_enabled': True,
    'email_provider': 'sendgrid',
    'email_api_key': 'sg_api_key_92jd83kf74js93kd',
    'email_from': 'notifications@awesome.app',
    'email_reply_to': 'support@awesome.app',
    'email_templates': '/templates/email',
    'push_enabled': True,
    'push_provider': 'fcm',
    'push_api_key': 'fcm_key_47ks93jd82kf74js',
    'push_certificate': '/certs/push.pem',
    'sms_enabled': True,
    'sms_provider': 'twilio',
    'sms_account_sid': 'twilio_sid_92jd83kf',
    'sms_auth_token': 'twilio_token_74js93kd',
    'sms_from_number': '+15551234567',
    'webhook_enabled': True,
    'webhook_retry_attempts': 3,
    'webhook_timeout': 10,
    'slack_enabled': True,
    'slack_webhook': 'https://hooks.slack.com/services/XXX',
    'discord_enabled': False,
    'discord_webhook': '',
    'telegram_enabled': False,
    'telegram_bot_token': '',
    'telegram_chat_id': '',
    'in_app_notifications': True,
    'notification_sound': 'default',
    'notification_badge': True,
    'notification_banner': True,
    'notification_history_limit': 100,
    'notification_retention_days': 30
}

billing_config = {
    'provider': 'stripe',
    'publishable_key': 'pk_live_92jd83kf74js93kd',
    'secret_key': 'sk_live_47ks93jd82kf74js',
    'webhook_secret': 'whsec_83jd92kf74js93kd',
    'currency': 'USD',
    'tax_enabled': True,
    'tax_rate': 0.08,
    'invoice_enabled': True,
    'invoice_prefix': 'INV-',
    'invoice_number_start': 1000,
    'payment_methods': ['card', 'bank_transfer', 'paypal'],
    'subscription_enabled': True,
    'trial_period_days': 14,
    'free_tier_enabled': True,
    'pricing_tiers': ['free', 'basic', 'pro', 'enterprise'],
    'basic_price': 9.99,
    'pro_price': 29.99,
    'enterprise_price': 99.99,
    'billing_cycle': 'monthly',
    'proration_enabled': True,
    'grace_period_days': 3,
    'failed_payment_retry': True,
    'max_retry_attempts': 3,
    'dunning_enabled': True,
    'refund_policy_days': 30,
    'cancellation_immediate': False,
    'cancellation_end_of_period': True,
    'discount_codes_enabled': True,
    'affiliate_program': False,
    'revenue_recognition': 'accrual',
    'accounting_integration': 'quickbooks'
}

experimental_features = {
    'quantum_encryption': False,
    'blockchain_storage': False,
    'neural_autocomplete': True,
    'holographic_display': False,
    'brain_interface': False,
    'time_travel_debug': False,
    'parallel_universe_testing': False,
    'ai_pair_programmer': True,
    'sentiment_analysis': False,
    'emotion_detection': False,
    'biometric_auth': True,
    'retina_scan': False,
    'fingerprint_auth': True,
    'facial_recognition': False,
    'voice_recognition': True,
    'behavioral_biometrics': False,
    'predictive_coding': True,
    'auto_bug_fix': False,
    'self_healing_code': False,
    'code_evolution': False,
    'genetic_algorithms': False,
    'swarm_intelligence': False,
    'quantum_computing': False,
    'edge_computing': True,
    'serverless_v2': True,
    'microservices_mesh': True,
    'service_mesh': True,
    'event_sourcing': False,
    'cqrs': False,
    'saga_pattern': False
}

